[package]
name = "eatyourgreens"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]


[target.'cfg(target_arch = "wasm32")'.dependencies]
enum-map = { version = "2.7.3", features = ["serde"] } # teleia needs this ???
glam = "*"
js-sys = "*"
log = "*"
rand = "*"
rand_chacha = "*"
serde = { version = "1.0.228", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
teleia = { path = "vendor/teleia/crates/teleia" }
teleia_macros = { path = "vendor/teleia/crates/teleia_macros" }
wasm-bindgen = "=0.2.100"
web-sys = { version = "0.3", features = [
    "Window",
    "Document",
    "HtmlVideoElement",
    "Element",
    "CssStyleDeclaration",
    "HtmlElement",
    "Blob",
    "BlobPropertyBag",
    "HtmlIFrameElement",
    "HtmlCollection",
    "Node",
    "Url",
] }
winit = { version = "=0.29.15" }
